//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatoSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatoSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function($){
        ///	$.fn.sayAccordion = function(options) {
        ///		var defaults = {
        ///			 aBtn: &apos;accordion-title&apos;,
        ///			 aContent: &apos;accordion-content&apos;,
        ///			 active: &apos;open&apos;
        ///		};
        ///		var options = $.extend({}, defaults, options);
        ///		$(document).ready(function() {
        ///			$(&apos;.&apos;+options.aContent).hide();
        ///			$(&apos;.&apos;+options.aBtn).each(function() {
        ///				if($(this).hasClass(options.active)){
        ///					$(this).siblings(&apos;.&apos;+options.aContent).addClass(options.active).slideDown();
        ///				}						  						  
        ///			});
        ///	   });
        ///	   $(&apos;.&apos;+optio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string accordion {
            get {
                return ResourceManager.GetString("accordion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bg_02 {
            get {
                object obj = ResourceManager.GetObject("bg_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_input {
            get {
                object obj = ResourceManager.GetObject("bg_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_input_focus {
            get {
                object obj = ResourceManager.GetObject("bg_input_focus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_jj {
            get {
                object obj = ResourceManager.GetObject("bg_jj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var current=&apos;&apos;;
        ///var current_service=&apos;&apos;;
        ///var current_cetak=&apos;&apos;;
        ///var service_id=&apos;5&apos;;
        ///var service_flag=&apos;&apos;;
        ///
        ///function resetservice()
        ///{
        ///	 $(&apos;.rollover2&apos;).each(function(i) {
        ///		service_id=&apos;5&apos;;
        ///		service_flag=&apos;&apos;;
        ///		$(this).attr(&apos;src&apos;,&apos;/asset/images/img/&apos;+$(this).attr(&apos;title&apos;).replace(&apos;-on&apos;,&apos;&apos;));
        ///	});
        ///}
        ///
        ///$(function(){
        ///	$(&apos;#btnCetak&apos;).click(function(){
        ///		var ok=true;
        ///		var nomorpolisi=$(&apos;#nomorpolisi&apos;).val();
        ///		var tipe=$(&apos;#tipe&apos;).val();
        ///		var merk=$(&apos;#merk&apos;).val()
        ///
        ///		if(nomorpolisi==&apos;&apos;)
        ///		{
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string checkin {
            get {
                return ResourceManager.GetString("checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var montharray=new Array(&quot;Januari&quot;,&quot;Februari&quot;,&quot;Maret&quot;,&quot;April&quot;,&quot;Mei&quot;,&quot;Juni&quot;,&quot;Juli&quot;,&quot;Agustus&quot;,&quot;September&quot;,&quot;Oktober&quot;,&quot;November&quot;,&quot;Desember&quot;)
        ///var serverdate=new Date(currenttime)
        ///
        ///function padlength(what){
        ///	var output=(what.toString().length==1)? &quot;0&quot;+what : what
        ///	return output
        ///}
        ///
        ///function displaytime(){
        ///	serverdate.setSeconds(serverdate.getSeconds()+1)
        ///	var datestring=padlength(serverdate.getDate())+&quot; &quot;+montharray[serverdate.getMonth()]+&quot; &quot;+serverdate.getFullYear()
        ///	var timestring=padlength(serverdate.getHours() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string current_time {
            get {
                return ResourceManager.GetString("current_time", resourceCulture);
            }
        }
        
        internal static byte[] current_time_js {
            get {
                object obj = ResourceManager.GetObject("current_time_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Facebox (for jQuery)
        /// * version: 1.2 (05/05/2008)
        /// * @requires jQuery v1.2 or later
        /// *
        /// * Examples at http://famspam.com/img/facebox/
        /// *
        /// * Licensed under the MIT:
        /// *   http://www.opensource.org/licenses/mit-license.php
        /// *
        /// * Copyright 2007, 2008 Chris Wanstrath [ chris@ozmm.org ]
        /// *
        /// * Usage:
        /// *  
        /// *  jQuery(document).ready(function() {
        /// *    jQuery(&apos;a[rel*=facebox]&apos;).facebox() 
        /// *  })
        /// *
        /// *  &lt;a href=&quot;#terms&quot; rel=&quot;facebox&quot;&gt;Terms&lt;/a&gt;
        /// *    Loads the #terms div in the box
        /// *
        /// *  &lt;a href=&quot;terms.html&quot; re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string facebox {
            get {
                return ResourceManager.GetString("facebox", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap header_top_sato {
            get {
                object obj = ResourceManager.GetObject("header_top_sato", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JJBSI {
            get {
                object obj = ResourceManager.GetObject("JJBSI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.7.1 jquery.com | jquery.org/license */
        ///(function(a,b){function cy(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cv(a){if(!ck[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){cl||(cl=c.createElement(&quot;iframe&quot;),cl.frameBorder=cl.width=cl.height=0),b.appendChild(cl);if(!cm||!cl.createElement)cm=(cl.contentWindow||cl.contentDocument).document,cm.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery JavaScript Library v1.3.2
        /// * http://jquery.com/
        /// *
        /// * Copyright (c) 2009 John Resig
        /// * Dual licensed under the MIT and GPL licenses.
        /// * http://docs.jquery.com/License
        /// *
        /// * Date: 2009-02-19 17:34:21 -0500 (Thu, 19 Feb 2009)
        /// * Revision: 6246
        /// */
        ///(function(){var l=this,g,y=l.jQuery,p=l.$,o=l.jQuery=l.$=function(E,F){return new o.fn.init(E,F)},D=/^[^&lt;]*(&lt;(.|\s)+&gt;)[^&gt;]*$|^#([\w-]+)$/,f=/^.[^:#\[\.,]*$/;o.fn=o.prototype={init:function(E,H){E=E||document;if(E.nodeType){this[0]=E;this.length=1;this.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_3_2_min {
            get {
                return ResourceManager.GetString("jquery_1_3_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.8.2
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2012 jQuery Foundation and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: Thu Sep 20 2012 21:13:05 GMT-0400 (Eastern Daylight Time)
        /// */
        ///(function( window, undefined ) {
        ///var
        ///	// A central reference to the root jQuery(document)
        ///	rootjQuery,
        ///
        ///	// The deferred used on DOM ready
        ///	readyList,
        ///
        ///	// Use the correct document accordingly with wind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_8_2 {
            get {
                return ResourceManager.GetString("jquery_1_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI Datepicker 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI/Datepicker
        /// *
        /// * Depends:
        /// *	ui.core.js
        /// */
        ///(function($){$.extend($.ui,{datepicker:{version:&quot;1.7.2&quot;}});var PROP_NAME=&quot;datepicker&quot;;function Datepicker(){this.debug=false;this._curInst=null;this._keyEvent=false;this._disabledInputs=[];this._datepickerShowing=false;this._inDialog=false;this._main [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_datepicker {
            get {
                return ResourceManager.GetString("jquery_datepicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Flash (http://jquery.lukelutman.com/plugins/flash)
        /// * A jQuery plugin for embedding Flash movies.
        /// * 
        /// * Version 1.0
        /// * November 9th, 2006
        /// *
        /// * Copyright (c) 2006 Luke Lutman (http://www.lukelutman.com)
        /// * Dual licensed under the MIT and GPL licenses.
        /// * http://www.opensource.org/licenses/mit-license.php
        /// * http://www.opensource.org/licenses/gpl-license.php
        /// * 
        /// * Inspired by:
        /// * SWFObject (http://blog.deconcept.com/swfobject/)
        /// * UFO (http://www.bobbyvandersluis.com/ufo/)
        /// * sIFR (http://www.mikein [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_flash {
            get {
                return ResourceManager.GetString("jquery_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Form Plugin
        /// * version: 2.33 (22-SEP-2009)
        /// * @requires jQuery v1.2.6 or later
        /// *
        /// * Examples and documentation at: http://malsup.com/jquery/form/
        /// * Dual licensed under the MIT and GPL licenses:
        /// *   http://www.opensource.org/licenses/mit-license.php
        /// *   http://www.gnu.org/licenses/gpl.html
        /// */
        ///;(function($) {
        ///
        ////*
        ///	Usage Note:
        ///	-----------
        ///	Do not use both ajaxSubmit and ajaxForm on the same form.  These
        ///	functions are intended to be exclusive.  Use ajaxSubmit if you want
        ///	to bind your own su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_form {
            get {
                return ResourceManager.GetString("jquery_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///(c) Copyrights 2007 - 2008
        ///
        ///Original idea by by Binny V A, http://www.openjs.com/scripts/events/keyboard_shortcuts/
        /// 
        ///jQuery Plugin by Tzury Bar Yochay 
        ///tzury.by@gmail.com
        ///http://evalinux.wordpress.com
        ///http://facebook.com/profile.php?id=513676303
        ///
        ///Project&apos;s sites: 
        ///http://code.google.com/p/js-hotkeys/
        ///http://github.com/tzuryby/hotkeys/tree/master
        ///
        ///License: same as jQuery license. 
        ///
        ///USAGE:
        ///    // simple usage
        ///    $(document).bind(&apos;keydown&apos;, &apos;Ctrl+c&apos;, function(){ alert(&apos;copy anyone?&apos;);});
        ///    
        ///    // speci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_hotkeys {
            get {
                return ResourceManager.GetString("jquery_hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(jQuery){jQuery.fn.__bind__=jQuery.fn.bind;jQuery.fn.__unbind__=jQuery.fn.unbind;jQuery.fn.__find__=jQuery.fn.find;var hotkeys={version:&apos;0.7.9&apos;,override:/keypress|keydown|keyup/g,triggersMap:{},specialKeys:{27:&apos;esc&apos;,9:&apos;tab&apos;,32:&apos;space&apos;,13:&apos;return&apos;,8:&apos;backspace&apos;,145:&apos;scroll&apos;,20:&apos;capslock&apos;,144:&apos;numlock&apos;,19:&apos;pause&apos;,45:&apos;insert&apos;,36:&apos;home&apos;,46:&apos;del&apos;,35:&apos;end&apos;,33:&apos;pageup&apos;,34:&apos;pagedown&apos;,37:&apos;left&apos;,38:&apos;up&apos;,39:&apos;right&apos;,40:&apos;down&apos;,109:&apos;-&apos;,112:&apos;f1&apos;,113:&apos;f2&apos;,114:&apos;f3&apos;,115:&apos;f4&apos;,116:&apos;f5&apos;,117:&apos;f6&apos;,118:&apos;f7&apos;,119:&apos;f8&apos;,120:&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_hotkeys_0_7_9_min {
            get {
                return ResourceManager.GetString("jquery_hotkeys_0_7_9_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(function($){$.fn.editable=function(target,options){if(&apos;disable&apos;==target){$(this).data(&apos;disabled.editable&apos;,true);return;}
        ///if(&apos;enable&apos;==target){$(this).data(&apos;disabled.editable&apos;,false);return;}
        ///if(&apos;destroy&apos;==target){$(this).unbind($(this).data(&apos;event.editable&apos;)).removeData(&apos;disabled.editable&apos;).removeData(&apos;event.editable&apos;);return;}
        ///var settings=$.extend({},$.fn.editable.defaults,{target:target},options);var plugin=$.editable.types[settings.type].plugin||function(){};var submit=$.editable.types[settings.type]. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_jeditable_mini {
            get {
                return ResourceManager.GetString("jquery_jeditable_mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* http://keith-wood.name/keypad.html
        ///   Keypad field entry extension for jQuery v1.2.0.
        ///   Written by Keith Wood (kbwood{at}iinet.com.au) August 2008.
        ///   Dual licensed under the GPL (http://dev.jquery.com/browser/trunk/jquery/GPL-LICENSE.txt) and 
        ///   MIT (http://dev.jquery.com/browser/trunk/jquery/MIT-LICENSE.txt) licenses. 
        ///   Please attribute the author if you use it. */
        ///(function($){var t=&apos;keypad&apos;;function Keypad(){this._curInst=null;this._disabledFields=[];this._keypadShowing=false;this.regional= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_keypad_min {
            get {
                return ResourceManager.GetString("jquery_keypad_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(d){d.fn.priceFormat=function(a){a=d.extend({prefix:&quot;US$ &quot;,suffix:&quot;&quot;,centsSeparator:&quot;.&quot;,thousandsSeparator:&quot;,&quot;,limit:!1,centsLimit:2,clearPrefix:!1,clearSufix:!1,allowNegative:!1},a);return this.each(function(){function g(k){for(var b=&quot;&quot;,a=0;a&lt;k.length;a++)char_=k.charAt(a),0==b.length&amp;&amp;0==char_&amp;&amp;(char_=!1),char_&amp;&amp;char_.match(t)&amp;&amp;(m?b.length&lt;m&amp;&amp;(b+=char_):b+=char_);for(var c;b.length&lt;j+1;)b=&quot;0&quot;+b;c=b;var b=&quot;&quot;,a=0,d=c.substr(c.length-j,j),e=c.substr(0,c.length-j);c=e+n+d;if(l){for(c=e.length;0&lt;
        ///c;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_price_format_1_7_min {
            get {
                return ResourceManager.GetString("jquery_price_format_1_7_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eval(function(p,a,c,k,e,r){e=function(c){return(c&lt;a?&apos;&apos;:e(parseInt(c/a)))+((c=c%a)&gt;35?String.fromCharCode(c+29):c.toString(36))};if(!&apos;&apos;.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return&apos;\\w+&apos;};c=1};while(c--)if(k[c])p=p.replace(new RegExp(&apos;\\b&apos;+e(c)+&apos;\\b&apos;,&apos;g&apos;),k[c]);return p}(&apos;(9($){2 q=9(a){2 b=a.w;2 d=b.8;2 e=[];6(2 i=0;i&lt;d;i++){2 f=b[i].Z;2 g=f.8;6(2 j=0;j&lt;g;j++){2 c=f[j];2 h=c.12||1;2 n=c.10||1;2 o=-1;3(!e[i]){e[i]=[]}2 m=e[i];z(m[++o]){}c.E=o;6(2 k=i;k&lt;i+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_tablehover_pack {
            get {
                return ResourceManager.GetString("jquery_tablehover_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI Effects 1.7.2
        /// *
        /// * Copyright (c) 2009 AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * http://docs.jquery.com/UI/Effects/
        /// */
        ///jQuery.effects||(function(d){d.effects={version:&quot;1.7.2&quot;,save:function(g,h){for(var f=0;f&lt;h.length;f++){if(h[f]!==null){g.data(&quot;ec.storage.&quot;+h[f],g[0].style[h[f]])}}},restore:function(g,h){for(var f=0;f&lt;h.length;f++){if(h[f]!==null){g.css(h[f],g.data(&quot;ec.storage.&quot;+h[f]))}}},setMode:fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_1_7_2_custom_min {
            get {
                return ResourceManager.GetString("jquery_ui_1_7_2_custom_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery UI CSS Framework @VERSION
        /// *
        /// * Copyright 2010, AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * http://docs.jquery.com/UI/Theming/API
        /// */
        ///
        ////* Layout helpers
        ///----------------------------------*/
        ///.ui-helper-hidden { display: none; }
        ///.ui-helper-hidden-accessible { position: absolute; left: -99999999px; }
        ///.ui-helper-reset { margin: 0; padding: 0; border: 0; outline: 0; line-height: 1.3; text-decoratio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_1_8_16_custom {
            get {
                return ResourceManager.GetString("jquery_ui_1_8_16_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery UI 1.8.18
        /// *
        /// * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * http://docs.jquery.com/UI
        /// */(function(a,b){function d(b){return!a(b).parents().andSelf().filter(function(){return a.curCSS(this,&quot;visibility&quot;)===&quot;hidden&quot;||a.expr.filters.hidden(this)}).length}function c(b,c){var e=b.nodeName.toLowerCase();if(&quot;area&quot;===e){var f=b.parentNode,g=f.name,h;if(!b.href||!g||f.nodeName.toLowerCase()!==&quot;map&quot;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_1_8_18_custom_min {
            get {
                return ResourceManager.GetString("jquery_ui_1_8_18_custom_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(e,t){&quot;use strict&quot;;function n(e){var t=Array.prototype.slice.call(arguments,1);return e.prop?e.prop.apply(e,t):e.attr.apply(e,t)}function s(e,t,n){var s,a;for(s in n)n.hasOwnProperty(s)&amp;&amp;(a=s.replace(/ |$/g,t.eventNamespace),e.bind(s,n[s]))}function a(e,t,n){s(e,n,{focus:function(){t.addClass(n.focusClass)},blur:function(){t.removeClass(n.focusClass),t.removeClass(n.activeClass)},mouseenter:function(){t.addClass(n.hoverClass)},mouseleave:function(){t.removeClass(n.hoverClass),t.removeClass(n.active [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_uniform_min {
            get {
                return ResourceManager.GetString("jquery_uniform_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery validation plug-in 1.5.5
        /// *
        /// * http://bassistance.de/jquery-plugins/jquery-plugin-validation/
        /// * http://docs.jquery.com/Plugins/Validation
        /// *
        /// * Copyright (c) 2006 - 2008 JÃ¶rn Zaefferer
        /// *
        /// * $Id: jquery.validate.js 6403 2009-06-17 14:27:16Z joern.zaefferer $
        /// *
        /// * Dual licensed under the MIT and GPL licenses:
        /// *   http://www.opensource.org/licenses/mit-license.php
        /// *   http://www.gnu.org/licenses/gpl.html
        /// */
        ///eval(function(p,a,c,k,e,r){e=function(c){return(c&lt;a?&apos;&apos;:e(parseInt(c/a)))+((c=c%a)&gt;35 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_validate_pack {
            get {
                return ResourceManager.GetString("jquery_validate_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var current=&apos;&apos;;
        ///var current_service=&apos;&apos;;
        ///var current_cetak=&apos;&apos;;
        ///var service_id=&apos;5&apos;;
        ///var service_flag=&apos;&apos;;
        ///
        ///function resetservice()
        ///{
        ///	 $(&apos;.rollover2&apos;).each(function(i) {
        ///		service_id=&apos;5&apos;;
        ///		service_flag=&apos;&apos;;
        ///		$(this).attr(&apos;src&apos;,&apos;/img/&apos;+$(this).attr(&apos;title&apos;).replace(&apos;-on&apos;,&apos;&apos;));
        ///	});
        ///}
        ///
        ///$(function(){
        ///	$(&apos;#cetak&apos;).click(function(){
        ///		var ok=true;
        ///		var nomorpolisi=$(&apos;#nomorpolisi&apos;).val();
        ///		var tipe=$(&apos;#tipe&apos;).val();
        ///		var merk=$(&apos;#merk&apos;).val()
        ///
        ///		if(nomorpolisi==&apos;&apos;)
        ///		{
        ///			alert(&apos;Nomor Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string masuk {
            get {
                return ResourceManager.GetString("masuk", resourceCulture);
            }
        }
        
        internal static byte[] masuk_js {
            get {
                object obj = ResourceManager.GetObject("masuk_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var current=&apos;&apos;;
        ///var current_service=&apos;&apos;;
        ///var current_cetak=&apos;&apos;;
        ///var service_id=&apos;0&apos;;
        ///var service_flag=&apos;&apos;;
        ///
        ///function resetservice()
        ///{
        ///	 $(&apos;.rollover2&apos;).each(function(i) {
        ///		service_id=&apos;0&apos;;
        ///		service_flag=&apos;&apos;;
        ///		$(this).attr(&apos;src&apos;,&apos;/img/&apos;+$(this).attr(&apos;title&apos;).replace(&apos;-on&apos;,&apos;&apos;));
        ///	});
        ///}
        ///
        ///$(function(){
        ///	$(&apos;#cetak&apos;).click(function(){
        ///		var ok=true;
        ///		var nomorpolisi=$(&apos;#nomorpolisi&apos;).val();
        ///		if(nomorpolisi==&apos;&apos;)
        ///		{
        ///			alert(&apos;Nomor Polisi belum dimasukkan. Silahkan masukkan dahulu&apos;);
        ///			$(&apos;#no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string masukori {
            get {
                return ResourceManager.GetString("masukori", resourceCulture);
            }
        }
        
        internal static byte[] masukori_js {
            get {
                object obj = ResourceManager.GetObject("masukori_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satologo {
            get {
                object obj = ResourceManager.GetObject("satologo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satologo1 {
            get {
                object obj = ResourceManager.GetObject("satologo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap satologo11 {
            get {
                object obj = ResourceManager.GetObject("satologo11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///   SoundManager 2: Javascript Sound for the Web
        ///   --------------------------------------------
        ///   http://schillmania.com/projects/soundmanager2/
        ///
        ///   Copyright (c) 2008, Scott Schiller. All rights reserved.
        ///   Code licensed under the BSD License:
        ///   http://schillmania.com/projects/soundmanager2/license.txt
        ///
        ///   V2.95a.20090717
        ///*/
        ///
        ///var soundManager = null;
        ///
        ///function SoundManager(smURL,smID) {
        /// 
        ///  this.flashVersion = 8;           // version of flash to require, either 8 or 9. Some API featu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string soundmanager2 {
            get {
                return ResourceManager.GetString("soundmanager2", resourceCulture);
            }
        }
        
        internal static byte[] soundmanager2_js {
            get {
                object obj = ResourceManager.GetObject("soundmanager2_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** @license
        /// *
        /// * SoundManager 2: JavaScript Sound for the Web
        /// * ----------------------------------------------
        /// * http://schillmania.com/projects/soundmanager2/
        /// *
        /// * Copyright (c) 2007, Scott Schiller. All rights reserved.
        /// * Code provided under the BSD License:
        /// * http://schillmania.com/projects/soundmanager2/license.txt
        /// *
        /// * V2.97a.20130101
        /// */
        ///
        ////*global window, SM2_DEFER, sm2Debugger, console, document, navigator, setTimeout, setInterval, clearInterval, Audio, opera */
        ////*jslint regexp: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string soundmanager2_nodebug {
            get {
                return ResourceManager.GetString("soundmanager2_nodebug", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Thickbox 3 - One Box To Rule Them All.
        /// * By Cody Lindley (http://www.codylindley.com)
        /// * Copyright (c) 2007 cody lindley
        /// * Licensed under the MIT License: http://www.opensource.org/licenses/mit-license.php
        ///*/
        ///
        ///var tb_pathToImage = &quot;/img/loadingAnimation.gif&quot;;
        ///
        ///eval(function(p,a,c,k,e,r){e=function(c){return(c&lt;a?&apos;&apos;:e(parseInt(c/a)))+((c=c%a)&gt;35?String.fromCharCode(c+29):c.toString(36))};if(!&apos;&apos;.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return&apos;\\w+&apos;};c= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thickbox_compressed {
            get {
                return ResourceManager.GetString("thickbox_compressed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_flat_0_aaaaaa_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_0_aaaaaa_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_flat_75_ffffff_40x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_75_ffffff_40x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_glass_55_fbf9ee_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_55_fbf9ee_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_glass_65_ffffff_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_65_ffffff_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_glass_75_dadada_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_dadada_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_glass_75_e6e6e6_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_e6e6e6_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_glass_95_fef1ec_1x400 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_95_fef1ec_1x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_75_cccccc_1x100 {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_75_cccccc_1x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_icons_222222_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_222222_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_icons_2e83ff_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_2e83ff_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_icons_454545_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_454545_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_icons_888888_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_888888_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ui_icons_cd0a0a_256x240 {
            get {
                object obj = ResourceManager.GetObject("ui_icons_cd0a0a_256x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] vendors {
            get {
                object obj = ResourceManager.GetObject("vendors", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
